name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: aswa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- App: detect lockfile (controls caching/ci vs install) ----------
      - id: app_lock
        name: Check app lockfile
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      # ---------- App: setup Node ----------
      - name: Setup Node for app (cached)
        if: steps.app_lock.outputs.present == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup Node for app (no cache)
        if: steps.app_lock.outputs.present != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- App: install & build ----------
      - name: Install app deps (ci)
        if: steps.app_lock.outputs.present == 'true'
        run: npm ci

      - name: Install app deps (install)
        if: steps.app_lock.outputs.present != 'true'
        run: npm install

      - name: Build app
        run: npm run build
        # If your build output folder is NOT "dist", update app_artifact_location below to match.

      # ---------- API: (OPTION A) Let SWA build the Functions app ----------
      # Keep your api folder at ./api with:
      #   - host.json (e.g. { "version": "2.0" })
      #   - package.json (Node)
      #   - each function in its own folder with function.json + code

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload

          # Paths in your repo
          app_location: "/"             # your SPA/static app root
          api_location: "api"           # Functions folder ("" if you have NO API)
          app_artifact_location: "dist" # change if your app build outputs elsewhere

          # We built the app above, so skip only the app build.
          skip_app_build: true
          # IMPORTANT: do NOT skip the API build — omit or set to false
          # skip_api_build: false
