name: build_and_deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- APP (frontend) ----------
      - name: Setup Node for app
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            package-lock.json

      - name: Install app deps
        run: npm ci

      - name: Build app
        run: npm run build
        # If your build output folder isn't "dist", adjust the next step's app_artifact_location

      # ---------- API (functions) ----------
      - name: Setup Node for api
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            api/package-lock.json

      - name: Install API deps (production)
        working-directory: api
        run: npm ci --omit=dev

      # ---------- DEPLOY (skip Oryx builds) ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          # Paths
          app_location: "/"
          api_location: "api"
          app_artifact_location: "dist"   # <— change if your Vite output folder is different

          # Skip Oryx builds (we already built/installed)
          skip_app_build: true
          skip_api_build: true
