name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
  workflow_dispatch:

# Ensure only ONE deploy runs; older runs get auto-cancelled
concurrency:
  group: swa-prod
  cancel-in-progress: true

jobs:
  build_and_deploy:
    name: Build and deploy web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (Vite)
        run: npm run build

      # Deploy the built /web/dist without re-building in Oryx
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "web"
          output_location: "dist"
          skip_app_build: true
