name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18 for API
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build API (ts -> dist) and keep only prod deps
        working-directory: api
        run: |
          npm install --no-audit --no-fund
          npm run build
          npm prune --omit=dev

      # 🔎 Show exactly what we’re about to deploy
      - name: Show API payload
        run: |
          echo "== api root =="
          ls -la api
          echo "== host.json =="
          test -f api/host.json && cat api/host.json || (echo "MISSING: api/host.json"; exit 1)
          echo "== function.json files =="
          find api -maxdepth 2 -name function.json | sort
          echo "== compiled JS (dist) =="
          find api/dist -type f | sort | head -n 200

      # ✅ Hard validation: every function.json must resolve to a real compiled JS file
      - name: Validate function.json scriptFile targets
        run: |
          set -e
          command -v jq >/dev/null 2>&1 || { echo "Installing jq..."; sudo apt-get update -y && sudo apt-get install -y jq; }
          missing=0
          for f in $(find api -maxdepth 2 -name function.json | sort); do
            sf=$(jq -r '.scriptFile // empty' "$f")
            if [ -z "$sf" ]; then
              echo "ERROR: $f has no scriptFile"
              missing=1
              continue
            fi
            base=$(dirname "$f")
            target="$base/$sf"
            if [ ! -f "$target" ]; then
              echo "ERROR: $f -> scriptFile '$sf' not found at '$target'"
              # show nearby files for context
              echo "Nearby files in $(dirname "$target"):"
              ls -la "$(dirname "$target")" || true
              missing=1
            else
              echo "OK: $f -> $target"
            fi
          done
          exit $missing

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: web
          skip_app_build: true
          api_location: api
          skip_api_build: true
