name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install & build frontend
        working-directory: web
        run: |
          npm ci --no-audit --no-fund || npm install --no-audit --no-fund
          npm run build
      - name: Install & compile API
        working-directory: api
        run: |
          npm ci --no-audit --no-fund || npm install --no-audit --no-fund
          if [ -f tsconfig.json ]; then
            npx --yes --package typescript tsc -p .
          else
            echo "No tsconfig.json, skipping TypeScript compile"
          fi
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: web
          api_location: api
          output_location: dist
