name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Build and Deploy
    env:
      NODE_VERSION: '18'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for API build)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Build ONLY the API from its source folder.
      # (Use npm install, since there is no api/package-lock.json)
      - name: Install API deps
        run: npm install --no-audit --no-fund
        working-directory: api

      - name: Build API (TypeScript)
        run: npm run build
        working-directory: api

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload

          # Frontend: serve /web as-is (no build)
          app_location: web
          skip_app_build: true
          config_file_location: web/staticwebapp.config.json

          # API: point to source folder (language detected from package.json),
          # but we already built above, so skip the action's own build.
          api_location: api
          skip_api_build: true

          production_branch: main

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR Environment
    steps:
      - name: Close Azure Static Web Apps PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
