name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Azure/static-web-apps-deploy@v1
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload

          # Web: you already have a simple index.html so don't rebuild it
          app_location: web
          skip_app_build: true

          # API: point to api (the source); let Oryx detect Node and run the build command
          api_location: api
          skip_api_build: false
          api_build_command: >
            npm ci --omit=dev --no-audit --no-fund
            && npx tsc -p tsconfig.json
