name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------
      # Build API (Azure Functions)
      # -----------------------------
      - name: Setup Node (for API build)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build API
        working-directory: api
        run: |
          set -euxo pipefail

          # Install deps: prefer npm ci when a lockfile exists; otherwise create one
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi

          # Compile TS -> JS (expects tsconfig to output to ./dist)
          npm run build

          # Ensure function.json files are present in dist
          rsync -a --include='*/' --include='function.json' --exclude='*' ./ ./dist/

          # Host config at the root of the function app
          cp -f host.json ./dist/host.json

          # Keep only runtime deps in the artifact
          npm prune --omit=dev
          cp -f package.json ./dist/package.json
          cp -R node_modules ./dist/node_modules

      # -----------------------------
      # Deploy app + prebuilt API
      # -----------------------------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "web"
          api_location: "api/dist"
          skip_app_build: true
          skip_api_build: true
          production_branch: "main"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR Environment
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
