name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18 for API build
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Validate function.json syntax (pre-build)
        shell: bash
        run: |
          set -e
          shopt -s globstar nullglob
          for f in api/**/function.json; do
            echo "Checking JSON: $f"
            node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$f"
          done

      - name: Build API (ts -> js) and keep only prod deps
        working-directory: api
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
          npx tsc -p tsconfig.json
          npm prune --omit=dev

      - name: Validate function.json scriptFile targets (post-build)
        shell: bash
        run: |
          set -e
          shopt -s globstar nullglob
          for f in api/**/function.json; do
            dir="$(dirname "$f")"
            sf="$(node -e "const j=require(process.argv[1]);process.stdout.write((j.scriptFile||'').trim());" "$f")"
            if [ -z "$sf" ]; then
              echo "Error: scriptFile missing in $f"
              exit 1
            fi
            if [ ! -f "$dir/$sf" ]; then
              echo "Error: scriptFile path not found: $dir/$sf (from $f)"
              echo "Directory listing for $dir:"
              ls -la "$dir"
              exit 1
            fi
            echo "OK $f -> $sf"
          done

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: web
          skip_app_build: true
          api_location: api
          skip_api_build: true
          function_language: 'node'
          # Remove the next line if you don't have this file
          config_file_location: web/staticwebapp.config.json

      - name: Smoke test API (/api/ping)
        if: ${{ vars.SWA_URL != '' }}
        shell: bash
        run: |
          set -e
          echo "Pinging ${{ vars.SWA_URL }}/api/ping"
          curl -fsSL "${{ vars.SWA_URL }}/api/ping" | tee /tmp/ping.json
          node -e "JSON.parse(require('fs').readFileSync('/tmp/ping.json','utf8'))"

      - name: Smoke test web (home page)
        if: ${{ vars.SWA_URL != '' }}
        shell: bash
        run: |
          set -e
          echo "Fetching ${{ vars.SWA_URL }}/"
          curl -fsS "${{ vars.SWA_URL }}/" | head -c 400 >/dev/null

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
