name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # With cache if a lockfile exists
      - name: Use Node 18 (cached)
        if: hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      # Fallback: no cache (prevents the lockfile error)
      - name: Use Node 18 (no cache)
        if: hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') == ''
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # --- Pre-build: validate every function.json
      - name: Validate function.json syntax (pre-build)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(api/*/function.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No api/*/function.json files found; skipping."
            exit 0
          fi
          for f in "${files[@]}"; do
            echo "Validating $f"
            jq empty "$f"
          done
          echo "All function.json files are valid ✅"

      # Optional app install/build — runs only if package.json + lockfile exist
      - name: Install front-end deps (optional)
        if: hashFiles('package.json') != '' && hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != ''
        run: npm ci

      - name: Build front-end (optional)
        if: hashFiles('package.json') != ''
        run: |
          npm run build || echo "No build script; SWA will try to build during deploy."

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"          # adjust if app in subfolder
          api_location: "api"
          output_location: "dist"    # change to build/ or out/ if your build outputs there

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Azure Static Web Apps PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
