name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # All run steps work inside /web
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (web)
        run: npm install --no-audit --no-fund

      - name: Build app (web)
        run: npm run build

      # Ensure SPA routing & any settings are included in the deployed artifact
      # (copy your existing config into the dist root)
      - name: Copy static web app config into dist
        run: |
          if [ -f staticwebapp.config.json ]; then
            cp staticwebapp.config.json dist/
          fi

      # Deploy the **built** app (web/dist), do NOT build again on Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "web/dist"   # <<< deploy the build output
          skip_app_build: true
          skip_api_build: true
