name: Build and deploy web

on:
  push:
    branches: [ main ]
    paths:
      - "web/**"
      - ".github/workflows/build-and-deploy-web.yml"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        working-directory: web
        run: |
          npm install

      - name: Build (Vite)
        working-directory: web
        run: npm run build

      # We already built, so skip Oryx. Just upload /web/dist
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "web"
          output_location: "dist"
          skip_app_build: true
