name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  id-token: write
  pull-requests: write

# Avoid piling up concurrent deploys on the same branch
concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    # Only deploy on push, or on an open/sync PR (not when a PR is closed)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for API build)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build the Functions API (TypeScript → JS in api/dist)
      - name: Build API (TypeScript → dist)
        working-directory: api
        run: |
          npm install --no-audit --no-fund
          # If you have "build": "tsc -p tsconfig.json" this will run it,
          # otherwise fallback to a direct tsc call.
          npm run build || npx tsc -p tsconfig.json
          # Ensure function.json files are included next to compiled JS
          rsync -a --include="*/" --include="function.json" --exclude="*" ./ ./dist/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # needed for PR comments
          action: "upload"
          app_location: "web"       # your static site root
          api_location: "api/dist"  # the prebuilt Functions app
          output_location: ""       # no frontend build output folder (raw files in web/)

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
