name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node for any prebuild checks you run yourself
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      # --- Pre-build: validate every function.json
      - name: Validate function.json syntax (pre-build)
      - shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(api/*/function.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No api/*/function.json files found; skipping."
            exit 0
          fi
          for f in "${files[@]}"; do
            echo "Validating $f"
            jq empty "$f"
          done
          echo "All function.json files are valid ✅"

      # Optional: install front-end deps to speed up SWA build (SWA can do this itself via Oryx,
      # but doing it here gives you faster, cached installs and build-time failures earlier)
      - name: Install front-end deps (optional)
        if: hashFiles('package-lock.json') != ''
        run: npm ci

      - name: Build front-end (optional)
        if: hashFiles('package.json') != '' && hashFiles('package-lock.json') != ''
        run: |
          # Pick ONE of the following build outputs and set OUTPUT_LOCATION below:
          # - Vite / most modern bundlers: npm run build -> dist/
          # - CRA: npm run build -> build/
          # - Next.js (static export): npm run build && npm run export -> out/
          npm run build || echo "No build script; SWA Oryx will try to build during deploy."

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # Where your app source lives. If your front-end is at repo root, leave "/".
          app_location: "/"
          # Where your API lives relative to repo root.
          api_location: "api"
          # Set this to match your build tool’s output:
          # - "dist" for Vite (default here)
          # - "build" for CRA
          # - "out" for Next.js export
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Azure Static Web Apps PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
