name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18 for API
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build API (ts -> dist) and keep only prod deps
        working-directory: api
        run: |
          npm install --no-audit --no-fund
          npm run build
          npm prune --omit=dev

      # 🔎 Debug: show exactly what we’re about to deploy for the API
      - name: Show API payload
        run: |
          echo "== api root =="
          ls -la api
          echo "== dist (compiled JS) =="
          find api/dist -maxdepth 2 -type f | sort || true
          echo "== sample function.json locations =="
          find api -maxdepth 2 -name function.json | sort

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: web
          skip_app_build: true
          api_location: api
          skip_api_build: true
