name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build API ourselves so Oryx doesn't try to run tsc
      - name: Use Node 18 for API build
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build API (compile TS in-place; then prune dev deps)
        working-directory: api
        shell: bash
        run: |
          set -e
          # If lockfile exists use ci, else install
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
          npx tsc -p tsconfig.json
          # remove devDeps before deploy
          npm prune --omit=dev

      # Deploy and explicitly skip any builds (no Oryx tsc)
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload

          app_location: web
          skip_app_build: true
          app_build_command: 'echo "skip app build"'

          api_location: api
          skip_api_build: true
          api_build_command: 'echo "skip api build"'
