name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    # Don’t run this job on PR close (SWA uses a separate "close" action)
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Keep Node around for any tiny scripts we run (no cache to avoid lockfile errors)
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Simple sanity check: validate all function.json files
      - name: Validate function.json syntax (pre-build)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(api/*/function.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No api/*/function.json files found; skipping."
            exit 0
          fi
          for f in "${files[@]}"; do
            echo "Validating $f"
            jq empty "$f"
          done
          echo "All function.json files are valid ✅"

      # Deploy with explicit action
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"        # change if your app is in a subfolder
          api_location: "api"      # Azure Functions lives here
          output_location: "dist"  # change to "build" (CRA) or "out" (Next export); or "" to let SWA serve root

  # Close PR environment on PR close
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Azure Static Web Apps PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
