name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (web)
        run: npm install --no-audit --no-fund

      - name: Build app (web)
        run: npm run build

      # Copy SPA config into dist so Azure uses it
      - name: Copy SPA config into dist
        run: |
          if [ -f staticwebapp.config.json ]; then
            cp staticwebapp.config.json dist/
          fi

      # Sanity check: ensure dist has what we expect
      - name: Verify built assets
        run: |
          test -f dist/index.html || (echo "dist/index.html missing" && exit 1)
          test -f dist/hubspot-theme.css || (echo "hubspot-theme.css missing in dist" && exit 1)
          echo "OK: dist has index.html and hubspot-theme.css"

      # 🚀 Upload the *built* folder only
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "web/dist"   # <- deploy dist only
          skip_app_build: true
          skip_api_build: true
