name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -----------------------------
      # Build API (Azure Functions)
      # -----------------------------
      - name: Setup Node (for API build)
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Functions v4 uses Node 18 on Linux

      - name: Build API
        working-directory: api
        run: |
          # Install all deps (incl. dev) to compile TypeScript
          npm ci

          # Compile TS -> JS (outputs to ./dist per your tsconfig)
          npm run build

          # Ensure every function.json is present in dist
          rsync -a --include='*/' --include='function.json' --exclude='*' ./ ./dist/

          # Host config must be at the root of the function app
          cp -f host.json ./dist/host.json

          # Prepare runtime-only dependencies for deployment
          npm prune --omit=dev

          # Copy runtime deps + package.json into dist
          cp -f package.json ./dist/package.json
          cp -R node_modules ./dist/node_modules

      # -----------------------------
      # Deploy app + prebuilt API
      # -----------------------------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "web"          # your static site root (already has index.html)
          api_location: "api/dist"      # prebuilt Functions artifact
          skip_app_build: true          # don't rebuild the static app
          skip_api_build: true          # <-- crucial: do NOT try to build in dist again
          production_branch: "main"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR Environment
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
