name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Build app
        run: npm run build

      # Detect common build output folders and pick the first that has an index.html
      - name: Detect app artifact directory
        run: |
          set -e
          OUT=""
          for d in dist build out .output/public; do
            if [ -d "$d" ] && find "$d" -type f -name index.html | head -n1 >/dev/null 2>&1; then
              OUT="$d"; break
            fi
          done
          if [ -z "$OUT" ] && [ -d dist ]; then
            SUB=$(find dist -maxdepth 2 -type f -name index.html | head -n1 || true)
            if [ -n "$SUB" ]; then OUT=$(dirname "$SUB"); fi
          fi
          if [ -z "$OUT" ]; then
            echo "No built app found (dist/build/out/.output/public or dist/<project>)" >&2
            exit 1
          fi
          echo "OUTPUT_DIR=$OUT" >> $GITHUB_ENV
          echo "Using OUTPUT_DIR=$OUT"

      - name: Debug output listing
        run: |
          echo "== $OUTPUT_DIR =="
          ls -la "$OUTPUT_DIR" || true
          find "$OUTPUT_DIR" -maxdepth 2 -type f | head -n 50 || true

      # FRONTEND-ONLY DEPLOY (temporarily disable API to isolate CDN issue)
      - name: Deploy to Azure Static Web Apps (frontend only)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /
          app_artifact_location: ${{ env.OUTPUT_DIR }}
          api_location: ""
          skip_app_build: true
