name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.action != 'closed'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- FRONTEND ----------
      - name: Install & build frontend
        id: web_build
        working-directory: web
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
          npm run build

      # ---------- API (optional TypeScript) ----------
      - name: Install & compile API
        id: api_build
        working-directory: api
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci --no-audit --no-fund
            else
              npm install --no-audit --no-fund
            fi
            if [ -f tsconfig.json ]; then
              npx --yes --package typescript tsc -p .
            else
              echo "No tsconfig.json in /api – skipping TypeScript compile."
            fi
          else
            echo "No /api/package.json – skipping API step."
          fi

      # ---------- DEPLOY ----------
      - name: Deploy to Azure Static Web Apps
        if: ${{ success() && secrets.AZURE_STATIC_WEB_APPS_API_TOKEN != '' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: web
          api_location: api
          output_location: dist

      - name: Skip deployment (missing token)
        if: ${{ success() && secrets.AZURE_STATIC_WEB_APPS_API_TOKEN == '' }}
        run: echo "AZURE_STATIC_WEB_APPS_API_TOKEN not set; skipping deployment."
