name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: aswa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- App: detect lockfile (controls caching/ci vs install) ----------
      - id: app_lock
        name: Check app lockfile
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      # ---------- App: setup Node (cache if lockfile exists) ----------
      - name: Setup Node for app (cached)
        if: steps.app_lock.outputs.present == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup Node for app (no cache)
        if: steps.app_lock.outputs.present != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- App: install & build ----------
      - name: Install app deps (ci)
        if: steps.app_lock.outputs.present == 'true'
        run: npm ci

      - name: Install app deps (install)
        if: steps.app_lock.outputs.present != 'true'
        run: npm install

      - name: Build app
        run: npm run build
        # If your build output folder is NOT "dist", update app_artifact_location below to match.

      # ---------- API: detect lockfile ----------
      - id: api_lock
        name: Check API lockfile
        shell: bash
        run: |
          if [ -f api/package-lock.json ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      # ---------- API: setup Node (cache if lockfile exists) ----------
      - name: Setup Node for api (cached)
        if: steps.api_lock.outputs.present == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Setup Node for api (no cache)
        if: steps.api_lock.outputs.present != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ---------- API: install production deps (no dev) ----------
      - name: Install API deps (ci, prod)
        if: steps.api_lock.outputs.present == 'true'
        working-directory: api
        run: npm ci --omit=dev

      - name: Install API deps (install, prod)
        if: steps.api_lock.outputs.present != 'true'
        working-directory: api
        run: npm install --omit=dev

      # ---------- Deploy (skip Oryx builds because we built above) ----------
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"            # path to your SPA/static app
          api_location: "api"          # path to your API folder ("" if none)
          app_artifact_location: "dist" # <- change if your app build outputs elsewhere
          skip_app_build: true
          skip_api_build: true
