      - name: Validate function.json scriptFile targets (post-build)
        shell: bash
        run: |
          set -e
          shopt -s globstar nullglob
          for f in api/**/function.json; do
            dir="$(dirname "$f")"
            # Read the JSON file as a path, not a module id
            sf="$(node -e "const fs=require('fs');const p=process.argv[1];const j=JSON.parse(fs.readFileSync(p,'utf8'));process.stdout.write((j.scriptFile||'').trim());" "$f")"
            if [ -z "$sf" ]; then
              echo "Error: scriptFile missing in $f"
              exit 1
            fi
            if [ ! -f "$dir/$sf" ]; then
              echo "Error: scriptFile path not found: $dir/$sf (from $f)"
              echo "Directory listing for $dir:"
              ls -la "$dir"
              exit 1
            fi
            echo "OK $f -> $sf"
          done
