name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node is used by Oryx during build; keep it simple (no caching needed)
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Optional sanity check: validate any function.json files
      - name: Validate function.json syntax (pre-build)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(api/*/function.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No api/*/function.json files found; skipping."
            exit 0
          fi
          for f in "${files[@]}"; do
            echo "Validating $f"
            jq empty "$f"
          done
          echo "All function.json files are valid ✅"

      # Deploy app + API
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # your frontend lives at the repo root
          output_location: "dist"    # Vite build output
          api_location: "api"        # <-- THIS ENSURES /api/** FUNCTIONS DEPLOY

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Azure Static Web Apps PR environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
