name: Build and deploy web

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - '.github/workflows/azure-static-web-apps.yml'
  workflow_dispatch:

# ensure only the newest run deploys, older ones are cancelled
concurrency:
  group: swa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable && pnpm i --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (Vite)
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: web
          output_location: dist
          config_file_location: web
