name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    # Run for pushes, or for PRs that are not being closed
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    concurrency:
      group: swa-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup Node (for API build)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ---- Build the Functions API into api/dist ----
      - name: Build API
        working-directory: api
        shell: bash
        run: |
          set -euo pipefail
          npm ci --no-audit --no-fund
          npm run build
          # Put runtime metadata into the artifact so Oryx can detect Node and install prod deps
          cp package.json dist/
          if [ -f package-lock.json ]; then cp package-lock.json dist/; fi
          # Include all function.json files in the artifact
          rsync -a --include='*/' --include='function.json' --exclude='*' ./ ./dist/
          echo '--- api/dist content (top level) ---'
          find dist -maxdepth 2 -type f | sort

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # for PR comments
          action: upload
          app_location: web          # your static site lives here
          api_location: api/dist     # deploy the compiled Functions app
          output_location: ""        # no separate front-end build output
          skip_app_build: true       # web is static; skip Oryx build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
