name: SWA Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Let the SWA action do the build with Oryx (uses npm install, not npm ci)
      - name: Build & Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "web"         # your app root
          api_location: ""            # no API
          output_location: "dist"     # where Vite builds to
          skip_app_build: false
          app_build_command: "npm run build"
